version: '3.6'

services:
  auth_db:
    command: ["postgres", "-c", "log_statement=all"]

  centralcommand_db:
    command: ["postgres", "-c", "log_statement=all"]



  integrationtester:
    image: golang:1.17 
    environment: 
      - APIGATEWAY=http://apigateway:8081
    depends_on:
      - apigateway
    working_dir: /go/src/deblasis/stc-integrationtester
    volumes: 
      - .:/go/src/deblasis/stc-integrationtester
    command: bash -c 'while [[ "$$(curl --connect-timeout 2 -s -o /dev/null -w ''%{http_code}'' ${APIGATEWAY:-http://apigateway:8081}/health)" != "200" ]]; do echo ‚è≥; sleep 5; done; echo apigateway is ready!;make dockertest'
    networks:  
      net:    
